server:
  port: 8080
spring:
  application:
    name: user
  datasource:
    password: 'password'
    url: jdbc:postgresql://localhost:5433/user
    username: 'adboard_admin'
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        #format_sql: true
    #show-sql: true